project_id = "pginaazhujdtcjonxjrh"

[functions.spoiler-free-companion]
verify_jwt = false

[functions.search-content]
verify_jwt = false

[functions.actor-connect]
verify_jwt = false

[functions.sort-by-custom-filter]
verify_jwt = false

[functions.open-pack]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.process-subtitles]
verify_jwt = false

[functions.cache-season-summary]
verify_jwt = false

[functions.backfill-embeddings]
verify_jwt = false
